version: "3.7"
services:
  app1:
    build: .
    hostname: "n1.dev"
    environment:
      - RELEASE_NODE=app@n1.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:6699:6699"
  app2:
    build: .
    hostname: "n2.dev"
    environment:
      - RELEASE_NODE=app@n2.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:6670:6699"
  app3:
    build: .
    hostname: "n3.dev"
    environment:
      - RELEASE_NODE=app@n3.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:6671:6699"
networks:
  default:
    external: true
    name: cluster-net
